spring:
  application:
    name: book-api
  datasource:
    url: jdbc:mysql://10.116.64.14:13306/nhn_academy_4?serverTimezone=Asia/Seoul
    username: project_be10_team4
    password: uEUklnkbk*7*_O4H
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 10364

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

