spring:
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/project_be10_team4_dev?useSSL=false&serverTimezone=UTC
    username: project_be10_team4
    password: uEUklnkbk*7*_O4H

  application:
    name: book-api

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true

  elasticsearch:
    uris: s4.java21.net:9200
    username: elastic
    password: nhnacademy123!

  cloud:
    config:
      enabled: false


server:
  port: ${PORT:10364}

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10372/eureka/
#    healthcheck:
#      enabled: true
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${server.port}
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,shutdown

management:
  health:
    elasticsearch:
      enabled: false


logging:
  level:
    com.netflix.discovery: off
    com.netflix.eureka: off
    org.springframework.cloud.netflix.eureka: off
