-- src/main/resources/schema.sql

-- CATEGORIES 테이블 생성 (ID는 자동 증가하도록 설정)
CREATE TABLE categories (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                            name VARCHAR(255) UNIQUE NOT NULL,
                            parent_id BIGINT,
                            PRIMARY KEY (id)
);

-- BOOKS 테이블 생성 (page_count와 image_url 컬럼 추가)
CREATE TABLE books (
                       isbn VARCHAR(255) NOT NULL,
                       title VARCHAR(255) NOT NULL,
                       table_of_contents CLOB,
                       description CLOB,
                       author VARCHAR(255) NOT NULL,
                       publisher VARCHAR(255) NOT NULL,
                       publication_date DATE NOT NULL,
                       page_count INTEGER,       -- 추가
                       image_url VARCHAR(255),   -- 추가
                       original_price DOUBLE NOT NULL,
                       selling_price DOUBLE NOT NULL,
                       gift_wrapping_available BOOLEAN NOT NULL,
                       likes INTEGER NOT NULL,
                       PRIMARY KEY (isbn)
);

-- BOOK_TAGS 테이블 생성
CREATE TABLE book_tags (
                           book_isbn VARCHAR(255) NOT NULL,
                           tag VARCHAR(255) NOT NULL,
                           PRIMARY KEY (book_isbn, tag),
                           FOREIGN KEY (book_isbn) REFERENCES books (isbn) ON DELETE CASCADE
);

-- BOOK_CATEGORIES 조인 테이블 생성
CREATE TABLE book_categories (
                                 book_isbn VARCHAR(255) NOT NULL,
                                 category_id BIGINT NOT NULL,
                                 PRIMARY KEY (book_isbn, category_id),
                                 FOREIGN KEY (book_isbn) REFERENCES books (isbn) ON DELETE CASCADE,
                                 FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE
);