-- CATEGORIES 테이블 생성
CREATE TABLE categories (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                            name VARCHAR(255) UNIQUE NOT NULL,
                            parent_id BIGINT,
                            PRIMARY KEY (id)
);

-- BOOKS 테이블 생성
CREATE TABLE books (
                       isbn VARCHAR(255) NOT NULL,
                       title VARCHAR(255) NOT NULL,
                       table_of_contents CLOB,
                       description CLOB,
                       author VARCHAR(255) NOT NULL,
                       publisher VARCHAR(255) NOT NULL,
                       publication_date DATE NOT NULL,
                       page_count INTEGER,
                       image_url VARCHAR(255),
                       original_price DOUBLE NOT NULL,
                       selling_price DOUBLE NOT NULL,
                       gift_wrapping_available BOOLEAN NOT NULL,
                       likes INTEGER NOT NULL,
                       PRIMARY KEY (isbn)
);

-- TAGS 테이블 생성
CREATE TABLE tags (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                      name VARCHAR(255) UNIQUE NOT NULL,
                      PRIMARY KEY (id)
);

-- BOOK_TAGS_JOIN 조인 테이블 생성
CREATE TABLE book_tags_join (
                                book_isbn VARCHAR(255) NOT NULL,
                                tag_id BIGINT NOT NULL,
                                PRIMARY KEY (book_isbn, tag_id),
                                FOREIGN KEY (book_isbn) REFERENCES books (isbn) ON DELETE CASCADE,
                                FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE
);

-- BOOK_CATEGORIES 조인 테이블 생성 (이 부분이 추가되었습니다!)
CREATE TABLE book_categories (
                                 book_isbn VARCHAR(255) NOT NULL,
                                 category_id BIGINT NOT NULL,
                                 PRIMARY KEY (book_isbn, category_id),
                                 FOREIGN KEY (book_isbn) REFERENCES books (isbn) ON DELETE CASCADE,
                                 FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE
);

--- 좋아요 기능 추가를 위한 테이블 ---

-- USERS 테이블 생성
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       username VARCHAR(255) UNIQUE NOT NULL,
                       PRIMARY KEY (id)
);

-- LIKES 테이블 생성
CREATE TABLE likes (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       user_id BIGINT NOT NULL,
                       book_isbn VARCHAR(255) NOT NULL,
                       PRIMARY KEY (id),
                       UNIQUE (user_id, book_isbn), -- 한 사용자가 한 책에 중복 좋아요를 누르지 못하도록 제약 조건 추가
                       FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
                       FOREIGN KEY (book_isbn) REFERENCES books (isbn) ON DELETE CASCADE
);