### 키워드로 검색
GET http://localhost:10364/api/search/keyword?keyword=아기&sort=highestPrice&page=0&size=100
Content-Type: application/json

###카테고리 검색
GET http://localhost:10364/api/search/categories?category=3&sort=newest&page=0&size=100
Content-Type: application/json

